In [1]:
import numpy as np
import pandas as pd

In [2]:
wine = pd.read_csv('winequality-red.csv')
wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [3]:
X = wine.iloc[:,:-1]
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [4]:
Y = wine.iloc[:,-1:]
Y

quality
0           5
1           5
2           5
3           6
4           5
...       ...
1594        5
1595        6
1596        6
1597        5
1598        6

[1599 rows x 1 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split (X,Y, test_size = 0.10, random_state=0)

# Gini Index Method

In [97]:
from sklearn.tree import DecisionTreeClassifier
DT_C = DecisionTreeClassifier()
DT_C.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [98]:
Y_dash = DT_C.predict(X_test)

In [99]:
from sklearn.metrics import confusion_matrix,classification_report

In [100]:
confusion_matrix(Y_test, Y_dash)

array([[ 0,  0,  1,  0,  0,  0],
       [ 0,  0,  3,  2,  1,  0],
       [ 1,  3, 48, 10,  2,  0],
       [ 0,  4, 15, 48,  5,  1],
       [ 0,  1,  4,  1,  8,  0],
       [ 0,  0,  0,  1,  1,  0]], dtype=int64)

In [101]:
print(classification_report(Y_test, Y_dash))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         6
           5       0.68      0.75      0.71        64
           6       0.77      0.66      0.71        73
           7       0.47      0.57      0.52        14
           8       0.00      0.00      0.00         2

    accuracy                           0.65       160
   macro avg       0.32      0.33      0.32       160
weighted avg       0.66      0.65      0.65       160



In [14]:
from sklearn import metrics
print("Accuracy:",(metrics.accuracy_score(Y_test, Y_dash)*100))

Accuracy: 65.0


# Entropy Method

In [93]:
DT_C_Entropy = DecisionTreeClassifier(criterion='entropy')
DT_C_Entropy.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [94]:
DT_C_Entropy_dash = DT_C_Entropy.predict(X_test)

In [95]:
confusion_matrix(Y_test, DT_C_Entropy_dash)

array([[ 0,  0,  1,  0,  0,  0],
       [ 0,  2,  3,  1,  0,  0],
       [ 0,  1, 45, 17,  1,  0],
       [ 1,  1, 17, 44, 10,  0],
       [ 0,  0,  1,  5,  6,  2],
       [ 0,  0,  0,  1,  1,  0]], dtype=int64)

In [96]:
print(classification_report(Y_test, DT_C_Entropy_dash))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.50      0.33      0.40         6
           5       0.67      0.70      0.69        64
           6       0.65      0.60      0.62        73
           7       0.33      0.43      0.38        14
           8       0.00      0.00      0.00         2

    accuracy                           0.61       160
   macro avg       0.36      0.34      0.35       160
weighted avg       0.61      0.61      0.61       160



# Ensembling

In [126]:
from sklearn.ensemble import BaggingClassifier
DT_Bag = BaggingClassifier(base_estimator=DT_C, n_estimators=10)
DT_Bag.fit(X_train, Y_train)

C:\Users\muhil\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:645: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                        class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort='deprecated',
                                                        random_state=None,


In [127]:
DT_Bag_dash = DT_Bag.predict(X_test)

In [128]:
confusion_matrix(Y_test, DT_Bag_dash)

array([[ 0,  0,  0,  1,  0,  0],
       [ 0,  1,  1,  4,  0,  0],
       [ 0,  0, 53, 11,  0,  0],
       [ 0,  1, 19, 51,  2,  0],
       [ 0,  0,  0,  4,  8,  2],
       [ 0,  0,  0,  2,  0,  0]], dtype=int64)

In [129]:
print(classification_report(Y_test, DT_Bag_dash))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.50      0.17      0.25         6
           5       0.73      0.83      0.77        64
           6       0.70      0.70      0.70        73
           7       0.80      0.57      0.67        14
           8       0.00      0.00      0.00         2

    accuracy                           0.71       160
   macro avg       0.45      0.38      0.40       160
weighted avg       0.70      0.71      0.70       160



C:\Users\muhil\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
