In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv ('health_insurance_cost.csv')
data

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
data.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [5]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
data.sex=LE.fit_transform(data.sex)
data.smoker=LE.fit_transform(data.smoker)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   int32  
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   int32  
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int32(2), int64(2), object(1)
memory usage: 62.8+ KB


In [7]:
data['sex']=data['sex'].astype('category')
data['smoker']=data['smoker'].astype('category')

In [8]:
data.head()

age sex     bmi  children smoker     region      charges
0   19   0  27.900         0      1  southwest  16884.92400
1   18   1  33.770         1      0  southeast   1725.55230
2   28   1  33.000         3      0  southeast   4449.46200
3   33   1  22.705         0      0  northwest  21984.47061
4   32   1  28.880         0      0  northwest   3866.85520

In [9]:
data.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [10]:
data1 = data.drop('region',axis=1)
data1

age sex     bmi  children smoker      charges
0      19   0  27.900         0      1  16884.92400
1      18   1  33.770         1      0   1725.55230
2      28   1  33.000         3      0   4449.46200
3      33   1  22.705         0      0  21984.47061
4      32   1  28.880         0      0   3866.85520
...   ...  ..     ...       ...    ...          ...
1333   50   1  30.970         3      0  10600.54830
1334   18   0  31.920         0      0   2205.98080
1335   18   0  36.850         0      0   1629.83350
1336   21   0  25.800         0      0   2007.94500
1337   61   0  29.070         0      1  29141.36030

[1338 rows x 6 columns]

In [11]:
x=data1.iloc[:,:-1]
x.head()

age sex     bmi  children smoker
0   19   0  27.900         0      1
1   18   1  33.770         1      0
2   28   1  33.000         3      0
3   33   1  22.705         0      0
4   32   1  28.880         0      0

In [12]:
y=data1.iloc[:,-1:]
y.head()

charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

# Spliting the Data

In [13]:
from sklearn.model_selection import train_test_split
XTrain, XTest, Ytrain, Ytest = train_test_split (x,y, test_size= 0.1, random_state=1 )

In [14]:
XTrain

age sex     bmi  children smoker
355    46   1  27.600         0      0
1316   19   0  20.600         0      0
133    19   1  25.555         0      0
181    18   0  38.280         0      0
1133   52   0  18.335         0      0
...   ...  ..     ...       ...    ...
715    60   1  28.900         0      0
905    26   0  29.355         2      0
1096   51   0  34.960         2      1
235    40   0  22.220         2      1
1061   57   1  27.940         1      0

[1204 rows x 5 columns]

# Training

In [15]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit (XTrain, Ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Testing

In [16]:
ydash= LR.predict(XTest)
ydash

array([[ 3955.39529279],
       [12648.71260665],
       [12777.98424584],
       [13814.25681127],
       [  838.04020664],
       [31918.27949776],
       [13361.13449427],
       [11724.59268534],
       [ 3092.71850493],
       [29834.24349594],
       [11506.25677004],
       [17778.95258563],
       [ 9139.2947152 ],
       [ 8664.33088607],
       [ 3351.92599366],
       [10826.65002389],
       [ 3627.33050352],
       [ 7377.54945072],
       [15446.85975811],
       [14725.05819568],
       [11873.33380576],
       [33358.95351805],
       [ 8844.51304538],
       [ 9282.65647769],
       [ 2263.22263831],
       [ 7964.83582755],
       [ 9110.14099479],
       [11105.58069849],
       [ 7997.95577277],
       [ 3699.7401362 ],
       [14438.70937146],
       [ 6171.70062328],
       [34259.58906523],
       [26592.05722398],
       [33959.96762537],
       [ 9357.94929369],
       [30518.71350913],
       [27075.59058974],
       [15498.44436552],
       [33672.67001967],


In [17]:
Ytest

charges
559    1646.42970
1087  11353.22760
1020   8798.59300
460   10381.47870
802    2103.08000
...           ...
120    7740.33700
759   36307.79830
248    1832.09400
991    7144.86265
1118  38282.74950

[134 rows x 1 columns]

In [18]:
LR.coef_

array([[  261.42152323,  -253.05678378,   310.95252355,   473.70375394,
        23759.2005412 ]])

In [19]:
LR.intercept_

array([-11806.70002657])

In [20]:
from sklearn.metrics import r2_score,mean_squared_error
R2 = r2_score(Ytest, ydash)

In [21]:
R2*100

72.43841993662777

# Mean Squared Error (MSE)

In [22]:
MSE = mean_squared_error(Ytest, ydash)
MSE

43553840.5595153

# Root Mean Squared Error (RSME)

In [23]:
RSME = np.sqrt(mean_squared_error(Ytest, ydash))
RSME

6599.53335922437

In [24]:
data1.head()

age sex     bmi  children smoker      charges
0   19   0  27.900         0      1  16884.92400
1   18   1  33.770         1      0   1725.55230
2   28   1  33.000         3      0   4449.46200
3   33   1  22.705         0      0  21984.47061
4   32   1  28.880         0      0   3866.85520

In [25]:
ypredict=LR.predict(np.array([[28,1,33,3,0]]))
ypredict

array([[6942.59037913]])