In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

C:\Users\muhil\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
SN_ads = pd.read_csv('datasets_553985_1008952_Social_Network_Ads.csv')
SN_ads

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
SN_ads.Gender = LE.fit_transform(SN_ads.Gender)

In [4]:
SN_ads['Gender'] = SN_ads['Gender'].astype('category')

In [5]:
SN_ads

User ID Gender  Age  EstimatedSalary  Purchased
0    15624510      1   19            19000          0
1    15810944      1   35            20000          0
2    15668575      0   26            43000          0
3    15603246      0   27            57000          0
4    15804002      1   19            76000          0
..        ...    ...  ...              ...        ...
395  15691863      0   46            41000          1
396  15706071      1   51            23000          1
397  15654296      0   50            20000          1
398  15755018      1   36            33000          0
399  15594041      0   49            36000          1

[400 rows x 5 columns]

In [6]:
SN_ads['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [7]:
x = SN_ads.iloc[:,1:4]
x

Gender  Age  EstimatedSalary
0        1   19            19000
1        1   35            20000
2        0   26            43000
3        0   27            57000
4        1   19            76000
..     ...  ...              ...
395      0   46            41000
396      1   51            23000
397      0   50            20000
398      1   36            33000
399      0   49            36000

[400 rows x 3 columns]

In [8]:
y = SN_ads.iloc[:,-1:]
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Purchased  400 non-null    int64
dtypes: int64(1)
memory usage: 3.2 KB


In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split (x, y, test_size=0.30, random_state = 0)

In [47]:
from sklearn.svm import LinearSVC
Sup_Vec = LinearSVC()
Sup_Vec.fit(X_train, Y_train) 

C:\Users\muhil\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\muhil\anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [48]:
Y_dash = Sup_Vec.predict(X_test)
Y_dash

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [42]:
y_predict = Sup_Vec.predict(np.array([[1,19,19000]]))
y_predict

array([0], dtype=int64)

In [24]:
from sklearn.metrics import classification_report

In [27]:
print(classification_report(Y_test, Y_dash))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89        32
           1       0.00      0.00      0.00         8

    accuracy                           0.80        40
   macro avg       0.40      0.50      0.44        40
weighted avg       0.64      0.80      0.71        40



In [33]:
from sklearn.ensemble import BaggingClassifier
Sup_Bag = BaggingClassifier(base_estimator= Sup_Vec, n_estimators=10)
Sup_Bag.fit(X_train, Y_train)

C:\Users\muhil\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:645: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\muhil\anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\muhil\anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\muhil\anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\muhil\anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, 

BaggingClassifier(base_estimator=LinearSVC(C=1.0, class_weight=None, dual=True,
                                           fit_intercept=True,
                                           intercept_scaling=1,
                                           loss='squared_hinge', max_iter=1000,
                                           multi_class='ovr', penalty='l2',
                                           random_state=None, tol=0.0001,
                                           verbose=0),
                  bootstrap=True, bootstrap_features=False, max_features=1.0,
                  max_samples=1.0, n_estimators=10, n_jobs=None,
                  oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [34]:
Y_dash_Bag = Sup_Bag.predict(X_test)
Y_dash_Bag

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [35]:
print(classification_report(Y_test, Y_dash_Bag))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        32
           1       0.20      1.00      0.33         8

    accuracy                           0.20        40
   macro avg       0.10      0.50      0.17        40
weighted avg       0.04      0.20      0.07        40



C:\Users\muhil\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
from sklearn.ensemble import RandomForestClassifier
Sup_Ran = RandomForestClassifier(n_estimators=10)
Sup_Ran.fit(X_train, Y_train)

C:\Users\muhil\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [37]:
Y_dash_Ran = Sup_Bag.predict(X_test)
Y_dash_Ran

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [38]:
print(classification_report(Y_test, Y_dash_Ran))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        32
           1       0.20      1.00      0.33         8

    accuracy                           0.20        40
   macro avg       0.10      0.50      0.17        40
weighted avg       0.04      0.20      0.07        40



C:\Users\muhil\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
